export const UNIVERSITIES = [
  // Public Universities
  { id: "ug", name: "University of Ghana", abbr: "UG", type: "public" },
  { id: "knust", name: "Kwame Nkrumah University of Science and Technology", abbr: "KNUST", type: "public" },
  { id: "ucc", name: "University of Cape Coast", abbr: "UCC", type: "public" },
  { id: "uew", name: "University of Education, Winneba", abbr: "UEW", type: "public" },
  { id: "uds", name: "University for Development Studies", abbr: "UDS", type: "public" },
  { id: "umat", name: "University of Mines and Technology", abbr: "UMaT", type: "public" },
  { id: "upsa", name: "University of Professional Studies, Accra", abbr: "UPSA", type: "public" },
  { id: "uhas", name: "University of Health and Allied Sciences", abbr: "UHAS", type: "public" },
  { id: "uenr", name: "University of Energy and Natural Resources", abbr: "UENR", type: "public" },
  { id: "uesd", name: "University of Environment and Sustainable Development", abbr: "UESD", type: "public" },
  { id: "sdd-ubids", name: "Simon Diedong Dombo University of Business and Integrated Development Studies", abbr: "SDD-UBIDS", type: "public" },
  { id: "gimpa", name: "Ghana Institute of Management and Public Administration", abbr: "GIMPA", type: "public" },
  { id: "gctu", name: "Ghana Communication Technology University", abbr: "GCTU", type: "public" },
  { id: "unimac", name: "University of Media, Arts and Communication", abbr: "UniMAC", type: "public" },
  { id: "oug", name: "Open University of Ghana", abbr: "OUG", type: "public" },
  // Technical Universities
  { id: "atu", name: "Accra Technical University", abbr: "ATU", type: "technical" },
  { id: "btu", name: "Bolgatanga Technical University", abbr: "BTU", type: "technical" },
  { id: "cctu", name: "Cape Coast Technical University", abbr: "CCTU", type: "technical" },
  { id: "dhltu", name: "Dr. Hilla Limann Technical University", abbr: "DHLTU", type: "technical" },
  { id: "htu", name: "Ho Technical University", abbr: "HTU", type: "technical" },
  { id: "ktu", name: "Koforidua Technical University", abbr: "KTU", type: "technical" },
  { id: "kstu", name: "Kumasi Technical University", abbr: "KsTU", type: "technical" },
  { id: "stu", name: "Sunyani Technical University", abbr: "STU", type: "technical" },
  { id: "ttu", name: "Takoradi Technical University", abbr: "TTU", type: "technical" },
  { id: "tatu", name: "Tamale Technical University", abbr: "TaTU", type: "technical" },
  // Private Universities
  { id: "ashesi", name: "Ashesi University", abbr: "Ashesi", type: "private" },
  { id: "acity", name: "Academic City University", abbr: "ACity", type: "private" },
  { id: "ait", name: "Accra Institute of Technology", abbr: "AIT", type: "private" },
  { id: "anu", name: "All Nations University", abbr: "ANU", type: "private" },
  { id: "bluecrest", name: "BlueCrest University", abbr: "BlueCrest", type: "private" },
  { id: "cug", name: "Catholic University of Ghana", abbr: "CUG", type: "private" },
  { id: "cu", name: "Central University", abbr: "CU", type: "private" },
  { id: "csu", name: "Christian Service University", abbr: "CSU", type: "private" },
  { id: "duc", name: "Dominion University College", abbr: "DUC", type: "private" },
  { id: "egu", name: "Ensign Global University", abbr: "EGU", type: "private" },
  { id: "epuc", name: "Evangelical Presbyterian University College", abbr: "EPUC", type: "private" },
  { id: "gcu", name: "Garden City University", abbr: "GCU", type: "private" },
  { id: "gbuc", name: "Ghana Baptist University College", abbr: "GBUC", type: "private" },
  { id: "gcuc", name: "Ghana Christian University College", abbr: "GCUC", type: "private" },
  { id: "hcuc", name: "Heritage Christian University College", abbr: "HCUC", type: "private" },
  { id: "iucg", name: "Islamic University College, Ghana", abbr: "IUCG", type: "private" },
  { id: "kaaf", name: "KAAF University", abbr: "KAAF", type: "private" },
  { id: "ku", name: "Knutsford University", abbr: "KU", type: "private" },
  { id: "lug", name: "Lancaster University Ghana", abbr: "LUG", type: "private" },
  { id: "muc", name: "Maranatha University College", abbr: "MUC", type: "private" },
  { id: "mug", name: "Methodist University Ghana", abbr: "MUG", type: "private" },
  { id: "nibs", name: "Nobel International Business School", abbr: "NiBS", type: "private" },
  { id: "pu", name: "Pentecost University", abbr: "PU", type: "private" },
  { id: "puc", name: "Perez University College", abbr: "PUC", type: "private" },
  { id: "pug", name: "Presbyterian University, Ghana", abbr: "PUG", type: "private" },
  { id: "ruc", name: "Radford University College", abbr: "RUC", type: "private" },
  { id: "regent", name: "Regent University College of Science and Technology", abbr: "Regent", type: "private" },
  { id: "vvu", name: "Valley View University", abbr: "VVU", type: "private" },
  { id: "webster", name: "Webster University Ghana", abbr: "Webster Ghana", type: "private" },
  { id: "weuc", name: "West End University College", abbr: "WEUC", type: "private" },
  { id: "wiuc-gh", name: "Wisconsin International University College, Ghana", abbr: "WIUC-GH", type: "private" },
  { id: "zuc", name: "Zenith University College", abbr: "ZUC", type: "private" },
];

export type University = typeof UNIVERSITIES[0];
